# Generated by Django 5.2.8 on 2026-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_education_admin_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='تم تسجيل دخول الفعالية'),
        ),
        migrations.AddField(
            model_name='student',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول للفعالية'),
        ),
    ]
