# Generated by Django 5.2.8 on 2026-02-20 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_checked_in_student_checked_in_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ar', models.CharField(max_length=200, verbose_name='الاسم الكامل (عربي)')),
                ('full_name_en', models.CharField(max_length=200, verbose_name='الاسم الكامل (إنجليزي)')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('school', models.CharField(max_length=150, verbose_name='المدرسة')),
                ('education_admin', models.CharField(max_length=150, verbose_name='الإدارة التعليمية')),
                ('interests', models.TextField(blank=True, verbose_name='الاهتمامات والهوايات')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='students.student', verbose_name='الطالب المرتبط')),
            ],
            options={
                'verbose_name': 'طلب تسجيل طالب',
                'verbose_name_plural': 'طلبات تسجيل الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
