# Generated by Django 5.2.8 on 2026-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='في القائمة السوداء'),
        ),
    ]
