# Generated by Django 5.2.8 on 2026-02-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='السنة الدراسية'),
        ),
    ]
