# Generated by Django 5.2.8 on 2026-02-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_grade_studentregistration_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_certificate_banned',
            field=models.BooleanField(default=False, verbose_name='محروم من الشهادة'),
        ),
    ]
