# Generated by Django 5.2.8 on 2026-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cert_emails_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات إرسال الشهادة'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_cert_email_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر إرسال للشهادة'),
        ),
    ]
