# Generated by Django 5.2.8 on 2026-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_cert_emails_sent_student_last_cert_email_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
