# Generated by Django 5.2.8 on 2026-02-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوسام')),
                ('description', models.TextField(verbose_name='وصف الوسام')),
                ('icon', models.CharField(default='award', max_length=50, verbose_name='أيقونة الوسام (Lucide)')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='لون الوسام')),
                ('criteria_type', models.CharField(choices=[('points', 'نقاط محددة'), ('attendance_rate', 'نسبة حضور'), ('manual', 'يدوي (بواسطة الأدمن)')], default='manual', max_length=20, verbose_name='نوع المعيار')),
                ('criteria_value', models.PositiveIntegerField(default=0, verbose_name='قيمة المعيار (النقاط أو النسبة %)')),
            ],
            options={
                'verbose_name': 'وسام',
                'verbose_name_plural': 'الأوسمة',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحصول عليه')),
                ('is_seen_by_student', models.BooleanField(default=False, verbose_name='تمت رؤيته من قبل الطالب')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='students.badge', verbose_name='الوسام')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'وسام طالب',
                'verbose_name_plural': 'أوسمة الطلاب',
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
