# Generated by Django 5.2.8 on 2026-03-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_adminlog_event_broadcastmessage_event_and_more'),
        ('students', '0012_badge_studentbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.CreateModel(
            name='StudentEventStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='النقاط في هذه الفعالية')),
                ('checked_in', models.BooleanField(default=False, verbose_name='تم تسجيل الحضور')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الحضور')),
                ('is_certificate_generated', models.BooleanField(default=False, verbose_name='تم إصدار الشهادة')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stats', to='dashboard.event', verbose_name='الفعالية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stats', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إحصائيات طالب في فعالية',
                'verbose_name_plural': 'إحصائيات الطلاب في الفعاليات',
                'unique_together': {('student', 'event')},
            },
        ),
    ]
