# Generated by Django 5.2.8 on 2026-03-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_badge_event_studentregistration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='students.student', verbose_name='الطالب المرتبط'),
        ),
    ]
