# Generated by Django 5.2.8 on 2026-03-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_studentregistration_student'),
        ('workshops', '0006_workshop_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorkshopNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الكتابة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_notes', to='students.student', verbose_name='الطالب')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='workshops.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'مذكرة تعلم طالب',
                'verbose_name_plural': 'مذكرات تعلم الطلاب',
                'unique_together': {('student', 'workshop')},
            },
        ),
    ]
