# Generated by Django 5.2.8 on 2026-03-11 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_studentworkshopnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإزالة من الفعالية'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='removed_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإزالة من الفعالية'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='تمت الإزالة بواسطة'),
        ),
    ]

