# Generated by Django 5.2.8 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studentregistration_removed_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['event', 'status', 'removed_at'], name='students_st_event_i_6eb78c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['email'], name='students_st_email_a1046c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['phone_number'], name='students_st_phone_n_4d4630_idx'),
        ),
    ]
