# Generated by Django 5.2.8 on 2026-02-19 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='اسم الورشة')),
                ('room', models.CharField(max_length=50, verbose_name='القاعة')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('active', 'نشطة'), ('finished', 'منتهية')], default='upcoming', max_length=20, verbose_name='حالة الورشة')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workshops', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'ورشة',
                'verbose_name_plural': 'الورش',
            },
        ),
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('9-10', '9:00 – 10:00'), ('10-11', '10:00 – 11:00'), ('11-12', '11:00 – 12:00'), ('12-1', '12:00 – 1:00'), ('1-2', '1:00 – 2:00')], max_length=10, verbose_name='الفترة الزمنية')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='groups.group', verbose_name='المجموعة')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'جلسة ورشة',
                'verbose_name_plural': 'جلسات الورش',
                'unique_together': {('group', 'period')},
            },
        ),
    ]
