# Generated by Django 5.2.8 on 2026-02-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_points'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='points_per_session',
            field=models.PositiveIntegerField(default=10, verbose_name='النقاط لكل جلسة'),
        ),
        migrations.CreateModel(
            name='WorkshopFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='students.student', verbose_name='الطالب')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workshops.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'تقييم ورشة',
                'verbose_name_plural': 'تقييمات الورش',
                'unique_together': {('student', 'workshop')},
            },
        ),
    ]
