# Generated by Django 5.2.8 on 2026-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_points_per_session_workshopfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopsession',
            name='period',
            field=models.CharField(choices=[('9:00-9:40', '9:00 – 9:40 (تسجيل الدخول)'), ('9:40-10:25', '9:40 – 10:25 (الورشة الأولى)'), ('10:25-10:35', '10:25 – 10:35 (راحة)'), ('10:35-11:20', '10:35 – 11:20 (الورشة الثانية)'), ('11:20-12:00', '11:20 – 12:00 (نشاط ترفيهي)'), ('12:00-12:45', '12:00 – 12:45 (الورشة الثالثة)'), ('12:45-12:55', '12:45 – 12:55 (راحة)'), ('12:55-1:40', '12:55 – 1:40 (الورشة الرابعة)'), ('1:40-2:00', '1:40 – 2:00 (الختام)')], max_length=20, verbose_name='الفترة الزمنية'),
        ),
    ]
