# Generated by Django 5.2.8 on 2026-02-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshopsession_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان المصدر')),
                ('resource_type', models.CharField(choices=[('link', 'رابط خارجي'), ('code', 'كود برمجي'), ('presentation', 'ملف عرض'), ('video', 'فيديو تعليمي'), ('other', 'أخرى')], default='link', max_length=20, verbose_name='نوع المصدر')),
                ('url', models.URLField(verbose_name='رابط المصدر')),
                ('description', models.TextField(blank=True, verbose_name='وصف قصير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='workshops.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'مصدر تعليمي',
                'verbose_name_plural': 'المصادر التعليمية',
                'ordering': ['-created_at'],
            },
        ),
    ]
