# Generated by Django 5.2.8 on 2026-02-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshopresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='workshop_resources/', verbose_name='ملف المصدر'),
        ),
        migrations.AlterField(
            model_name='workshopresource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط المصدر'),
        ),
    ]
