# Generated by Django 5.2.8 on 2026-03-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_adminlog_event_broadcastmessage_event_and_more'),
        ('workshops', '0005_workshopresource_file_alter_workshopresource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='dashboard.event', verbose_name='الفعالية'),
        ),
    ]
