# Generated by Django 5.2.8 on 2026-03-18 00:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_central_team_form(apps, schema_editor):
    PublicForm = apps.get_model('public_screen', 'PublicForm')
    PublicFormField = apps.get_model('public_screen', 'PublicFormField')

    title = 'استمارة بيانات أعضاء الفريق التقني المركزي'
    form = PublicForm.objects.filter(title=title).first()
    if not form:
        token = uuid.uuid4().hex + uuid.uuid4().hex
        form = PublicForm.objects.create(
            title=title,
            description=(
                'برجاء ملء البيانات التالية بدقة كاملة، مع التأكد من صحة جميع البيانات والمرفقات قبل الإرسال، '
                'وذلك لاستكمال قاعدة بيانات أعضاء الفريق التقني المركزي واستخدامها في الأغراض التنظيمية الخاصة بالفريق.'
            ),
            token=token,
            is_active=True,
        )

    fields = [
        ('full_name', 'الاسم رباعي', 'short_text', True, None, ''),
        ('national_id', 'الرقم القومي', 'short_text', True, None, ''),
        ('student_code', 'كود الطالب', 'short_text', True, None, ''),
        ('school', 'المدرسة', 'short_text', True, None, ''),
        (
            'education_admin',
            'الإدارة التعليمية',
            'dropdown',
            True,
            [
                'بنها',
                'طوخ',
                'كفر شكر',
                'شبين القناطر',
                'الخانكة',
                'قها',
                'قليوب',
                'القناطر الخيرية',
                'غرب شبرا الخيمة',
                'شرق شبرا الخيمة',
                'الخصوص',
                'العبور',
            ],
            '',
        ),
        ('address', 'العنوان', 'paragraph', True, None, ''),
        (
            'grade',
            'الصف الدراسي',
            'dropdown',
            True,
            [
                '1-prep',
                '2-prep',
                '3-prep',
                '1-sec',
                '2-sec',
                '3-sec',
            ],
            '',
        ),
        ('phone', 'رقم الهاتف (واتساب)', 'short_text', True, None, ''),
        ('id_photo', 'صورة البطاقة', 'file', False, None, ''),
        ('birth_certificate_photo', 'صورة شهادة الميلاد', 'file', True, None, ''),
        ('position', 'المنصب (لو أنت عارف منصبك)', 'short_text', False, None, ''),
        (
            'skills',
            'كل اللي بتعرف تعمله',
            'paragraph',
            True,
            None,
            'مثال: تنظيم – تصميم – برمجة – مونتاج – تقديم – كتابة محتوى – إدارة سوشيال ميديا – تصوير – تدريب – علاقات عامة – دعم فني.',
        ),
        ('participated_before', 'هل سبق لك المشاركة في أنشطة أو فعاليات من قبل؟', 'radio', True, ['نعم', 'لا'], ''),
        ('previous_experience', 'لو نعم، اذكر أبرز المشاركات أو الخبرات السابقة', 'paragraph', False, None, ''),
        (
            'preferred_areas',
            'المجالات التي تفضل العمل بها داخل الفريق',
            'checkboxes',
            True,
            [
                'التنظيم',
                'العلاقات العامة',
                'التصميم',
                'البرمجة',
                'المونتاج',
                'التصوير',
                'كتابة المحتوى',
                'التدريب',
                'إدارة السوشيال ميديا',
                'الدعم الفني',
                'أخرى',
            ],
            '',
        ),
        (
            'device_available',
            'هل لديك جهاز يمكنك العمل من خلاله؟',
            'radio',
            True,
            ['هاتف فقط', 'لابتوب فقط', 'هاتف ولابتوب', 'لا يوجد حاليًا'],
            '',
        ),
        (
            'commitment',
            'هل تستطيع الالتزام بمهام الفريق والاجتماعات عند التكليف؟',
            'radio',
            True,
            ['نعم', 'إلى حد ما', 'لا'],
            '',
        ),
        ('notes', 'أي اقتراحات أو ملاحظات عندك', 'paragraph', False, None, ''),
        (
            'agreement',
            'إقرار بصحة البيانات',
            'agreement',
            True,
            None,
            'أقر بأن جميع البيانات المدخلة صحيحة، وأتحمل مسؤولية صحتها، وأوافق على استخدامها في الأغراض التنظيمية الخاصة بالفريق التقني المركزي.',
        ),
    ]

    existing_keys = set(PublicFormField.objects.filter(form=form).values_list('key', flat=True))
    for idx, (key, label, field_type, required, choices, help_text) in enumerate(fields, start=1):
        if key in existing_keys:
            continue
        PublicFormField.objects.create(
            form=form,
            key=key,
            label=label,
            field_type=field_type,
            required=required,
            choices=choices,
            help_text=help_text,
            order=idx,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='public_screen.publicform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('short_text', 'إجابة قصيرة'), ('paragraph', 'فقرة'), ('dropdown', 'قائمة منسدلة'), ('radio', 'اختيار من متعدد'), ('checkboxes', 'مربعات اختيار'), ('file', 'رفع ملف'), ('agreement', 'مربع إقرار')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='public_screen.publicform')),
            ],
            options={
                'ordering': ['order', 'label'],
                'unique_together': {('form', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PublicFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_file', models.FileField(blank=True, null=True, upload_to='public-forms/uploads/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='public_screen.publicformfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='public_screen.publicformsubmission')),
            ],
            options={
                'unique_together': {('submission', 'field')},
            },
        ),
        migrations.RunPython(create_central_team_form, noop_reverse),
    ]
