# Generated by Django 5.2.8 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_screen', '0001_public_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicform',
            name='custom_slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]

