# Generated by Django 5.2.8 on 2026-03-18 00:00

from django.db import migrations


def add_profile_photo_field(apps, schema_editor):
    PublicForm = apps.get_model('public_screen', 'PublicForm')
    PublicFormField = apps.get_model('public_screen', 'PublicFormField')

    forms = PublicForm.objects.filter(title='استمارة بيانات أعضاء الفريق التقني المركزي')
    for form in forms:
        profile_field, _ = PublicFormField.objects.get_or_create(
            form=form,
            key='profile_photo',
            defaults={
                'label': 'صورة شخصية للاستخدام الرسمي',
                'field_type': 'file',
                'required': True,
                'help_text': 'مطلوب رفع صورة شخصية واضحة للاستخدام الرسمي داخل الفريق.',
                'order': 9,
            },
        )
        profile_field.label = 'صورة شخصية للاستخدام الرسمي'
        profile_field.field_type = 'file'
        profile_field.required = True
        profile_field.help_text = 'مطلوب رفع صورة شخصية واضحة للاستخدام الرسمي داخل الفريق.'
        if not profile_field.order:
            profile_field.order = 9
        profile_field.save(update_fields=['label', 'field_type', 'required', 'help_text', 'order'])

        id_photo = PublicFormField.objects.filter(form=form, key='id_photo').first()
        birth = PublicFormField.objects.filter(form=form, key='birth_certificate_photo').first()
        if id_photo:
            id_photo.order = max(profile_field.order + 1, id_photo.order or 0)
            id_photo.save(update_fields=['order'])
        if birth:
            birth.order = max((id_photo.order if id_photo else profile_field.order) + 1, birth.order or 0)
            birth.save(update_fields=['order'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('public_screen', '0002_publicform_custom_slug'),
    ]

    operations = [
        migrations.RunPython(add_profile_photo_field, noop_reverse),
    ]

