# Generated by Django 5.2.8 on 2026-03-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_screen', '0003_central_form_profile_photo_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicformanswer',
            unique_together=set(),
        ),
    ]

