# Generated by Django 5.2.8 on 2026-03-18 00:00

from django.db import migrations


def add_birth_fields(apps, schema_editor):
    PublicForm = apps.get_model('public_screen', 'PublicForm')
    PublicFormField = apps.get_model('public_screen', 'PublicFormField')
    forms = PublicForm.objects.filter(title='استمارة بيانات أعضاء الفريق التقني المركزي')
    for form in forms:
        birth_date_field, _ = PublicFormField.objects.get_or_create(
            form=form,
            key='birth_date',
            defaults={
                'label': 'تاريخ الميلاد',
                'field_type': 'short_text',
                'required': True,
                'help_text': 'يتم تعبئته تلقائيًا من الرقم القومي.',
                'order': 3,
            },
        )
        birth_date_field.label = 'تاريخ الميلاد'
        birth_date_field.field_type = 'short_text'
        birth_date_field.required = True
        birth_date_field.help_text = 'يتم تعبئته تلقائيًا من الرقم القومي.'
        birth_date_field.order = 3
        birth_date_field.save(update_fields=['label', 'field_type', 'required', 'help_text', 'order'])

        birth_gov_field, _ = PublicFormField.objects.get_or_create(
            form=form,
            key='birth_governorate',
            defaults={
                'label': 'محافظة الميلاد',
                'field_type': 'short_text',
                'required': True,
                'help_text': 'يتم تعبئته تلقائيًا من الرقم القومي.',
                'order': 4,
            },
        )
        birth_gov_field.label = 'محافظة الميلاد'
        birth_gov_field.field_type = 'short_text'
        birth_gov_field.required = True
        birth_gov_field.help_text = 'يتم تعبئته تلقائيًا من الرقم القومي.'
        birth_gov_field.order = 4
        birth_gov_field.save(update_fields=['label', 'field_type', 'required', 'help_text', 'order'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('public_screen', '0004_remove_publicformanswer_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(add_birth_fields, noop_reverse),
    ]

