# Generated by Django 5.2.8 on 2026-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tech Day', max_length=150, verbose_name='اسم الفعالية')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='موعد بدء الفعالية')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='مكان الفعالية')),
                ('location_link', models.URLField(blank=True, verbose_name='رابط موقع الفعالية')),
            ],
            options={
                'verbose_name': 'إعدادات الفعالية',
                'verbose_name_plural': 'إعدادات الفعالية',
            },
        ),
    ]
