# Generated by Django 5.2.8 on 2026-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_eventsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('title', models.CharField(max_length=255, verbose_name='الوظيفة أو الصفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الدعوة')),
            ],
            options={
                'verbose_name': 'دعوة VIP',
                'verbose_name_plural': 'دعوات VIP',
                'ordering': ['-created_at'],
            },
        ),
    ]
