# Generated by Django 5.2.8 on 2026-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_vipinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipinvite',
            name='vip_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='وقت حضور الضيف'),
        ),
    ]
