# Generated by Django 5.2.8 on 2026-02-23 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_eventsettings_is_finished'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_notes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملاحظة متطوع',
                'verbose_name_plural': 'ملاحظات المتطوعين',
                'ordering': ['-created_at'],
            },
        ),
    ]
