# Generated by Django 5.2.8 on 2026-02-23 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_volunteernote'),
        ('students', '0006_student_is_blacklisted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='سبب المخالفة أو الوصف')),
                ('status', models.CharField(choices=[('pending', 'في انتظار مراجعة الإدارة'), ('resolved', 'تمت المعالجة')], default='pending', max_length=20, verbose_name='حالة المخالفة')),
                ('admin_action', models.CharField(blank=True, max_length=255, verbose_name='إجراء الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_violations', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_violations', to=settings.AUTH_USER_MODEL, verbose_name='تم الإبلاغ بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مخالفة طالب',
                'verbose_name_plural': 'مخالفات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
