# Generated by Django 5.2.8 on 2026-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_studentviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, verbose_name='رابط مجموعة الواتساب'),
        ),
    ]
