# Generated by Django 5.2.8 on 2026-02-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_eventsettings_whatsapp_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='arrival_time_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='وقت الحضور المتوقع'),
        ),
    ]
