# Generated by Django 5.2.8 on 2026-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_eventsettings_arrival_time_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للطلاب'),
        ),
    ]
