# Generated by Django 5.2.8 on 2026-02-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_eventsettings_max_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=500, verbose_name='المستلمون')),
                ('subject', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body_text', models.TextField(blank=True, verbose_name='نص الرسالة (Text)')),
                ('body_html', models.TextField(blank=True, verbose_name='نص الرسالة (HTML)')),
                ('error_message', models.TextField(blank=True, verbose_name='خطأ الإرسال')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'ملاحظة متطوع',
                'verbose_name_plural': 'ملاحظات المتطوعين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='volunteernote',
            options={},
        ),
        migrations.RemoveField(
            model_name='volunteernote',
            name='created_at',
        ),
    ]
