# Generated by Django 5.2.8 on 2026-02-28 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_failedemail_alter_volunteernote_options_and_more'),
        ('workshops', '0005_workshopresource_file_alter_workshopresource_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteernote',
            options={'ordering': ['-created_at'], 'verbose_name': 'ملاحظة متطوع', 'verbose_name_plural': 'ملاحظات المتطوعين'},
        ),
        migrations.AddField(
            model_name='volunteernote',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص الاستغاثة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('solved', 'تم الحل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_seen', models.BooleanField(default=False, verbose_name='تمت رؤيته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop', verbose_name='الورشة/القاعة')),
            ],
            options={
                'verbose_name': 'طلب استغاثة (SOS)',
                'verbose_name_plural': 'طلبات الاستغاثة (SOS)',
                'ordering': ['-created_at'],
            },
        ),
    ]
