# Generated by Django 5.2.8 on 2026-02-28 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_volunteernote_options_volunteernote_created_at_and_more'),
        ('students', '0011_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrequest',
            name='location_manual',
            field=models.CharField(blank=True, max_length=255, verbose_name='المكان (يدوي)'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='الطالب المعني'),
        ),
    ]
