# Generated by Django 5.2.8 on 2026-02-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_sosrequest_location_manual_sosrequest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrequest',
            name='admin_reply',
            field=models.TextField(blank=True, verbose_name='رد الإدارة'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='is_reply_seen',
            field=models.BooleanField(default=False, verbose_name='تم رؤية الرد'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الرد'),
        ),
    ]
