# Generated by Django 5.2.8 on 2026-02-28 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_sosrequest_admin_reply_sosrequest_is_reply_seen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص الإذاعة')),
                ('target', models.CharField(choices=[('all', 'الكل'), ('students', 'الطلاب فقط'), ('supervisors', 'المشرفين فقط'), ('volunteers', 'المتطوعين فقط')], default='all', max_length=20, verbose_name='الفئة المستهدفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط حالياً')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إذاعة داخلية (Broadcast)',
                'verbose_name_plural': 'الإذاعات الداخلية (Broadcasts)',
                'ordering': ['-created_at'],
            },
        ),
    ]
