# Generated by Django 5.2.8 on 2026-02-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='event_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات الفعالية'),
        ),
    ]
