# Generated by Django 5.2.8 on 2026-02-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_eventsettings_event_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='is_registration_closed',
            field=models.BooleanField(default=False, verbose_name='إغلاق التسجيل يدوياً'),
        ),
    ]
