# Generated by Django 5.2.8 on 2026-03-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_eventsettings_is_registration_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='auto_mark_sessions_on_check_in',
            field=models.BooleanField(default=False, verbose_name='تسجيل حضور الورش تلقائياً عند دخول الفعالية'),
        ),
    ]
