# Generated by Django 5.2.8 on 2026-03-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_eventsettings_auto_mark_sessions_on_check_in'),
        ('students', '0012_badge_studentbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsettings',
            name='auto_mark_sessions_on_check_in',
        ),
        migrations.CreateModel(
            name='StudentSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('attendance', 'مشكلة في الحضور'), ('certificate', 'مشكلة في الشهادة'), ('account', 'مشكلة في الحساب'), ('workshop', 'مشكلة في الورشة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='فئة المشكلة')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان المشكلة')),
                ('message', models.TextField(verbose_name='تفاصيل المشكلة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد المعالجة'), ('solved', 'تم الحل'), ('closed', 'مغلق')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_reply', models.TextField(blank=True, verbose_name='رد الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب دعم طالب',
                'verbose_name_plural': 'طلبات دعم الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
