# Generated by Django 5.2.8 on 2026-03-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_eventsettings_auto_mark_sessions_on_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='allow_group_points',
            field=models.BooleanField(default=True, verbose_name='السماح بإضافة نقاط للمجموعات'),
        ),
    ]
