# Generated by Django 5.2.8 on 2026-03-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_eventsettings_allow_group_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tech Day', max_length=150, verbose_name='اسم الفعالية')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='السنة')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='مكان الفعالية')),
                ('execution_number', models.PositiveIntegerField(default=1, verbose_name='رقم التنفيذ')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='رابط الأرشفة')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='موعد بدء الفعالية')),
                ('location_link', models.URLField(blank=True, verbose_name='رابط موقع الفعالية')),
                ('arrival_time_text', models.CharField(blank=True, max_length=100, verbose_name='وقت الحضور المتوقع')),
                ('whatsapp_group_link', models.URLField(blank=True, verbose_name='رابط مجموعة الواتساب')),
                ('event_instructions', models.TextField(blank=True, verbose_name='تعليمات الفعالية')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للطلاب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة حالياً')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('is_registration_closed', models.BooleanField(default=False, verbose_name='إغلاق التسجيل يدوياً')),
                ('allow_group_points', models.BooleanField(default=True, verbose_name='السماح بإضافة نقاط للمجموعات')),
                ('is_finished', models.BooleanField(default=False, verbose_name='تم إنهاء الفعالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فعالية',
                'verbose_name_plural': 'الفعاليات',
                'ordering': ['-created_at'],
            },
        ),
    ]
