# Generated by Django 5.2.8 on 2026-03-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AddField(
            model_name='studentsupportrequest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AddField(
            model_name='studentviolation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='dashboard.event', verbose_name='الفعالية'),
        ),
    ]
