# Generated by Django 5.2.8 on 2026-03-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_adminlog_event_broadcastmessage_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSettings',
        ),
    ]
