# Generated by Django 5.2.8 on 2026-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_notification_related_support_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة'),
        ),
        migrations.AddField(
            model_name='event',
            name='maintenance_facebook_url',
            field=models.URLField(default='https://facebook.com/edutechegypt', verbose_name='لينك الفيسبوك في الصيانة'),
        ),
    ]
