# Generated by Django 5.2.8 on 2026-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_event_is_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20, verbose_name='نظام التشغيل')),
                ('version_code', models.CharField(max_length=50, verbose_name='رقم الإصدار (e.g. 1.0.0)')),
                ('build_number', models.IntegerField(verbose_name='رقم البناء (Build Number)')),
                ('min_build_number', models.IntegerField(verbose_name='أقل رقم بناء مسموح به')),
                ('download_url', models.URLField(blank=True, verbose_name='رابط تحميل التحديث')),
                ('release_notes', models.TextField(blank=True, verbose_name='ملاحظات الإصدار')),
                ('is_force_update', models.BooleanField(default=False, verbose_name='تحديث إجباري')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
            ],
            options={
                'verbose_name': 'إصدار التطبيق',
                'verbose_name_plural': 'إصدارات التطبيق',
                'ordering': ['-build_number'],
                'unique_together': {('platform', 'build_number')},
            },
        ),
    ]
