# Generated by Django 5.2.8 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='app_releases/', verbose_name='ملف APK'),
        ),
    ]

