# Generated by Django 5.2.8 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_appversion_apk_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failedemail',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'بريد بانتظار الإرسال',
                'verbose_name_plural': 'الإيميلات بانتظار الإرسال',
            },
        ),
        migrations.AlterField(
            model_name='failedemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفشل'),
        ),
    ]

