# Generated by Django 5.2.8 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_failedemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_existing_students_registration',
            field=models.BooleanField(default=True, verbose_name='السماح للطلاب المسجلين سابقاً بالتسجيل'),
        ),
    ]

