# Generated by Django 5.2.8 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_event_allow_existing_students_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_education_admin_locked',
            field=models.BooleanField(default=False, verbose_name='قفل الإدارة التعليمية للتسجيل'),
        ),
        migrations.AddField(
            model_name='event',
            name='locked_education_admin',
            field=models.CharField(blank=True, default='العبور', max_length=150, verbose_name='الإدارة التعليمية المسموح بها'),
        ),
    ]

