# Generated by Django 5.2.8 on 2026-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_event_education_admin_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locked_education_admin',
            field=models.TextField(blank=True, default='العبور', verbose_name='الإدارات التعليمية المسموح بها'),
        ),
    ]
