# Generated by Django 5.2.8 on 2026-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المجموعة')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='الكود')),
                ('color', models.CharField(max_length=20, verbose_name='لون المجموعة')),
                ('max_students', models.PositiveIntegerField(default=25, verbose_name='الحد الأقصى للطلاب')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
            },
        ),
    ]
