# Generated by Django 5.2.8 on 2026-02-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='النقاط'),
        ),
    ]
