# Generated by Django 5.2.8 on 2026-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('primary', 'ابتدائي'), ('prep_sec', 'إعدادي وثانوي')], default='primary', max_length=20, verbose_name='المرحلة الدراسية'),
        ),
    ]
