# Generated by Django 5.2.8 on 2026-03-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_adminlog_event_broadcastmessage_event_and_more'),
        ('groups', '0003_group_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='dashboard.event', verbose_name='الفعالية'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=1, verbose_name='الكود'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('event', 'code')},
        ),
    ]
