# Generated by Django 5.2.8 on 2026-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب')], default='present', max_length=20, verbose_name='الحالة')),
                ('scanned_at', models.DateTimeField(verbose_name='وقت التسجيل')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'سجلات الحضور',
            },
        ),
    ]
